lists/urls.py
from django.conf.urls import url
from lists import views

#from django.contrib import admin


urlpatterns = [
    # Examples:
    # url(r'^$', 'superlists.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
#    url(r'^$', views.home_page, name='home'),
#    url(r'^lists/new$', views.new_list, name='new_list'),
#    url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
#    url(r'^lists/(\d+)/add_item$', views.add_item, name = 'add_item'),

	url(r'^new$', views.new_list, name='new_list'),
	url(r'^(\d+)/$', views.view_list, name='view_list'),
	url(r'(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

#from django.contrib import admin


urlpatterns = [
    # Examples:
    # url(r'^$', 'superlists.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    
#    url(r'^$', views.home_page, name='home'),
#    url(r'^lists/new$', views.new_list, name='new_list'),
#    url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
#    url(r'^lists/(\d+)/add_item$', views.add_item, name = 'add_item'),

	url(r'^$', list_views.home_page, name='home'),
	url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.db import models

# Create your models here.

class List(models.Model):
	pass



class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)
#	list = models.TextField(default='')

lists/views.py
#from django.http import HttpResponse
from django.shortcuts import redirect, render
from lists.models import Item, List

# Create your views here.
def add_item(request, list_id):
	list_ = List.objects.get(id=list_id)
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect('/lists/%d/' % (list_.id,))

def new_list(request):
	list_ = List.objects.create()
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect('/lists/%d/' % (list_.id,))

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)	
#	items = Item.objects.filter(id=list_id)

	item_label = ''
	if Item.objects.filter(list_id = list_id).count() == 0:
		item_label = 'yey, waktunya berlibur'
	elif Item.objects.filter(list_id = list_id).count() < 5:
		item_label = 'sibuk tapi santai'
	elif Item.objects.filter(list_id = list_id).count() >= 5:
		item_label = 'oh tidak'
	return render(request, 'list.html', {'list': list_, 'item_label':item_label})

def home_page(request):
#	if request.method == 'POST':
#		Item.objects.create(text=request.POST['item_text'])
#		return redirect('/lists/the-only-list-in-the-world/')
	
#	items = Item.objects.all()
	
	item_label = ''
#	if Item.objects.count() == 0:
	item_label = 'yey, waktunya berlibur'
#	elif Item.objects.count() < 5:
#		item_label = 'sibuk tapi santai'
#	elif Item.objects.count() >= 5:
#		item_label = 'oh tidak'
	return render(request, 'home.html', {'item_label': item_label})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>

	<body>
	<div class="container">

		<div class="row">
			<div class="col-md-6 col-md-offset-3 jumbotron">
				<div class="text-center">
					<h1>{% block header_text %}{% endblock %}</h1>
					<form method="POST" action="{% block form_action %}{% endblock %}">
						<input name="item_text" id="id_new_item" class="form_control input-lg" placeholder="Enter a to-do item"/>
					{% csrf_token %}
					</form>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				{% block table %}
				{% endblock %}
			</div>
		</div>
	</div>

	<center><h5>Comment:<h5>
	{{ item_label }}</center>
	</body>
</html>

lists/templates/home.html
<html>
	<head>
		<title>To-Do lists</title>
	</head>

	<body>
		{% extends 'base.html'%}

		{% block header_text %}Start a new To-Do{% endblock %}
		
		{% block form_action %}/lists/new{% endblock %}

		{{ item_label }}
		<!--<h1>Start a new To-Do list</h1>
		<form method="POST" action="/lists/new">
			<input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
		{% csrf_token %}
		</form>-->
		
	</body>
</html>

lists/templates/list.html
<html>
	<head>
		<title>To-Do lists</title>
	</head>

	<body>
		{% extends 'base.html' %}

		{% block header_text %}Your To-Do list{% endblock %}

		{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}

		{% block table %}

			<table id="id_list_table" class="table">
				{% for item in list.item_set.all %}
					<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
				{% endfor %}
			</table>
		{% endblock %}
	</body>
</html>